<h1>EDA - Salarios</h1>
<p>Análisis Exploratorio</p>
<p>Junio 2026</p>

<h1>Configuración y carga</h1>

<h2>Importar librerias</h2>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

<h2>Configuración general</h2>

In [3]:
# Mostrar todas las columnas
pd.set_option('display.max_columns', None)
# Redonder a dos decimales
pd.set_option('display.float_format', '{:.2f}'.format)

<h2>Estilos en los gráficos</h2>

In [4]:
sns.set_theme(style='whitegrid', palette='Set2')
plt.rcParams['figure.figsize'] = (10,5)
plt.rcParams['figure.dpi'] = 100

<h1>Carga del dataset</h1>

In [5]:
URL1 = './diabetes.csv'
URL2 = 'https://raw.githubusercontent.com/semilun4/EDA-Data-Science/refs/heads/main/Data/data_science.csv'


df = pd.read_csv(URL2)
print(' PRIMERAS 5 FILAS ')
df.head()
print(' MUESTRA ALEATORIA ')
df.sample(5, random_state=42)
print(' ÚLTIMAS 5 FILAS ')
df.tail()

 PRIMERAS 5 FILAS
 MUESTRA ALEATORIA
 ÚLTIMAS 5 FILAS

,timestamp,company,level,title,totalyearlycompensation,location,yearsofexperience,yearsatcompany,tag,basesalary,stockgrantvalue,bonus,gender,otherdetails,cityid,dmaid,rowNumber,Masters_Degree,Bachelors_Degree,Doctorate_Degree,Highschool,Some_College,Race_Asian,Race_White,Race_Two_Or_More,Race_Black,Race_Hispanic,Race,Education
62637,9/9/2018 11:52:32,Google,T4,Software Engineer,327000,"Seattle, WA",10.00,1.00,Distributed Systems (Back-End),155000.00,150000.00,22000.00,NaN,NaN,11527,819.00,1973,0,0,0,0,0,0,0,0,0,0,NaN,NaN
62638,9/13/2018 8:23:32,Microsoft,62,Software Engineer,237000,"Redmond, WA",2.00,2.00,Full Stack,146900.00,73200.00,16000.00,NaN,NaN,11521,819.00,2037,0,0,0,0,0,0,0,0,0,0,NaN,NaN
62639,9/13/2018 14:35:59,MSFT,63,Software Engineer,220000,"Seattle, WA",14.00,12.00,Full Stack,157000.00,25000.00,20000.00,NaN,NaN,11527,819.00,2044,0,0,0,0,0,0,0,0,0,0,NaN,NaN
62640,9/16/2018 16:10:35,Salesforce,Lead MTS,Software Engineer,280000,"San Francisco, CA",8.00,4.00,iOS,194688.00,57000.00,29000.00,NaN,NaN,7419,807.00,2097,0,0,0,0,0,0,0,0,0,0,NaN,NaN
62641,1/29/2019 5:12:59,apple,ict3,Software Engineer,200000,"Sunnyvale, CA",0.00,0.00,ML / AI,155000.00,27000.00,19000.00,Male,NaN,7472,807.00,5424,0,0,0,0,0,0,0,0,0,0,NaN,NaN

<h2>Tipos de datos y estructura</h2>

In [6]:
# Información del dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62642 entries, 0 to 62641
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   timestamp                62642 non-null  str
 1   company                  62637 non-null  str
 2   level                    62519 non-null  str
 3   title                    62642 non-null  str
 4   totalyearlycompensation  62642 non-null  int64
 5   location                 62642 non-null  str
 6   yearsofexperience        62642 non-null  float64
 7   yearsatcompany           62642 non-null  float64
 8   tag                      61772 non-null  str
 9   basesalary               62642 non-null  float64
 10  stockgrantvalue          62642 non-null  float64
 11  bonus                    62642 non-null  float64
 12  gender                   43102 non-null  str
 13  otherdetails             40134 non-null  str
 14  cityid                   62642 non-null  int64
 15  dmaid                    62640 non-null  float64
 16  rowNumber                62642 non-null  int64
 17  Masters_Degree           62642 non-null  int64
 18  Bachelors_Degree         62642 non-null  int64
 19  Doctorate_Degree         62642 non-null  int64
 20  Highschool               62642 non-null  int64
 21  Some_College             62642 non-null  int64
 22  Race_Asian               62642 non-null  int64
 23  Race_White               62642 non-null  int64
 24  Race_Two_Or_More         62642 non-null  int64
 25  Race_Black               62642 non-null  int64
 26  Race_Hispanic            62642 non-null  int64
 27  Race                     22427 non-null  str
 28  Education                30370 non-null  str
dtypes: float64(6), int64(13), str(10)
memory usage: 13.9 MB

In [7]:
# Tipos de datos por columna
print('=== TIPOS DE DATOS ===')
tipos = pd.DataFrame({
    'Columna'   : df.columns,
    'Tipo'      : df.dtypes.values,
    'No Nulos'  : df.notnull().sum().values,
    'Nulos'     : df.isnull().sum().values,
    '% Nulos'   : (df.isnull().sum().values / len(df) * 100).round(2)
})
tipos

=== TIPOS DE DATOS ===

                    Columna     Tipo  No Nulos  Nulos  % Nulos
0                 timestamp      str     62642      0     0.00
1                   company      str     62637      5     0.01
2                     level      str     62519    123     0.20
3                     title      str     62642      0     0.00
4   totalyearlycompensation    int64     62642      0     0.00
5                  location      str     62642      0     0.00
6         yearsofexperience  float64     62642      0     0.00
7            yearsatcompany  float64     62642      0     0.00
8                       tag      str     61772    870     1.39
9                basesalary  float64     62642      0     0.00
10          stockgrantvalue  float64     62642      0     0.00
11                    bonus  float64     62642      0     0.00
12                   gender      str     43102  19540    31.19
13             otherdetails      str     40134  22508    35.93
14                   cityid    int64     62642      0     0.00
15                    dmaid  float64     62640      2     0.00
16                rowNumber    int64     62642      0     0.00
17           Masters_Degree    int64     62642      0     0.00
18         Bachelors_Degree    int64     62642      0     0.00
19         Doctorate_Degree    int64     62642      0     0.00
20               Highschool    int64     62642      0     0.00
21             Some_College    int64     62642      0     0.00
22               Race_Asian    int64     62642      0     0.00
23               Race_White    int64     62642      0     0.00
24         Race_Two_Or_More    int64     62642      0     0.00
25               Race_Black    int64     62642      0     0.00
26            Race_Hispanic    int64     62642      0     0.00
27                     Race      str     22427  40215    64.20
28                Education      str     30370  32272    51.52